name: my-github-actions
on: push
jobs:
    my-first-job:
        runs-on: ubuntu-latest
        steps:
            -   name: Print the files
                run: ls -la
            -   name: Print hello world
                run: echo "Hello world"
    
