name: my-github-actions
on: push
jobs:
    my-first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print the files
              run: ls -la
            - name: Print hello world
              run: echo "Hello world"
    my-second-job:
        runs-on: ubuntu-latest
        needs: my-first-job
        steps:
            - name: Node version
              run: node -v
            - name: create a app.js file
              run: touch app.js
            - name: Print files
              run: ls- a
